apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: back-test-svc
spec:
  type: NodePort
  selector:
    app: back-test # deployment file 안의 selector.app의 이름과 동일해야 한다. 
  ports:
  - protocol: TCP
    port: 80 # service port number
    targetPort: 8085 # port number of target pod in node 

